#!/usr/bin/env python3
# from typing import *



# def solve(A: int, B: int, W: int) -> List[str]:
def solve(A, B, W):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
a, b, w = map(int, input().split())
max = 0
min = 1001
for i in range(1, 10**6+1):
    if b*i >= w*1000 and b*(i-1) < w*1000:
        if min > i:
            min = i
    if a*i <= w*1000 and a*(i+1) > w*1000:
        if max < i:
            max = i
if min > max:
    print('UNSATISFIABLE')
else:
    print(min, max)

