#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 10 ** 9)  # TODO: edit here
    b = random.randint(1, 1000)  # TODO: edit here
    c = [None for _ in range(b)]
    d = [None for _ in range(b)]
    f = [None for _ in range(b)]
    g = [None for _ in range(b)]
    for i in range(b):
        c[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        d[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    e = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(b):
        f[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        g[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(a, end=' ')
    print(b, end=' ')
    for i in range(b):
        print(c[i])
        print(d[i], end=' ')
    print(e, end=' ')
    for i in range(b):
        print(f[i], g[i])

if __name__ == "__main__":
    main()
