a, b, c, d, e = map(int, input().split())
# num = set()
# num.add(e + d + c)
# num.add(e + d + b)
# num.add(e + d + a)
# num.add(e + c + b)
# num.add(e + c + a)
# num.add(e + b + a)
# num.add(d + c + b)
# num.add(d + c + a)
# num.add(d + b + a)
# num.add(c + b + a)
# num = list(num)
# num.sort(reverse=True)
# print(num[2])
# 模範解答
print(max(a + d + e, b + c + e))
